-- ============================================================================
-- SETUP RRHH: Calendarios, Turnos, Ausencias
-- ============================================================================

-- 1) Calendarios (festivos)
CREATE TABLE IF NOT EXISTS pr_calendarios (
    id_calendario bigint generated by default as identity primary key,
    id_organizacion bigint,
    nombre text not null,
    fecha date not null,
    tipo text default 'FESTIVO',
    descripcion text,
    created_at timestamptz default now()
);

-- 2) Turnos
CREATE TABLE IF NOT EXISTS pr_turnos (
    id_turno bigint generated by default as identity primary key,
    id_organizacion bigint,
    nombre text not null,
    hora_inicio time not null,
    hora_fin time not null,
    dias_semana text,
    activo boolean default true,
    created_at timestamptz default now()
);

-- 3) Ausencias
CREATE TABLE IF NOT EXISTS pr_ausencias (
    id_ausencia bigint generated by default as identity primary key,
    id_usuario text,
    tipo text default 'VACACIONES',
    fecha_inicio date not null,
    fecha_fin date not null,
    estado text default 'SOLICITADA',
    comentario text,
    created_at timestamptz default now()
);

-- Indices basicos
CREATE INDEX IF NOT EXISTS idx_calendarios_org_fecha ON pr_calendarios (id_organizacion, fecha);
CREATE INDEX IF NOT EXISTS idx_turnos_org ON pr_turnos (id_organizacion);
CREATE INDEX IF NOT EXISTS idx_ausencias_usuario ON pr_ausencias (id_usuario);
